/**
 * Generate 50 realistic Senegalese clients
 * @param {string} adminId - Admin user ObjectId for createdBy
 */
const getClientsData = (adminId) => {
  return [
    // === SEGMENT A — Top 20% (10 clients) ===
    { type: 'professionnel', raisonSociale: 'SONACOS SA', ninea: '00254871 2K3', rccm: 'SN-DKR-2018-A-45678', email: 'achat@sonacos.sn', phone: '+221 33 849 20 00', address: { street: 'Route de Rufisque', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'A', delaiPaiement: 60, plafondCredit: 50000000, modePaiement: 'virement', totalCA: 125000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Auchan Senegal', ninea: '00478523 1G2', rccm: 'SN-DKR-2015-B-78901', email: 'commandes@auchan.sn', phone: '+221 33 860 10 00', address: { street: 'Centre Commercial Sea Plaza', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', segment: 'A', delaiPaiement: 45, plafondCredit: 80000000, modePaiement: 'virement', totalCA: 98000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Casino Supermarche Dakar', ninea: '00367412 0H5', rccm: 'SN-DKR-2016-B-56234', email: 'approvisionnement@casino-dakar.sn', phone: '+221 33 867 00 00', address: { street: 'Avenue Cheikh Anta Diop', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', segment: 'A', delaiPaiement: 45, plafondCredit: 60000000, modePaiement: 'virement', totalCA: 85000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'SEDIMA SARL', ninea: '00289456 1K7', rccm: 'SN-DKR-2010-A-23456', email: 'direction@sedima.sn', phone: '+221 33 951 14 14', address: { street: 'Zone Industrielle', city: 'Thies', region: 'Thies', country: 'Senegal' }, category: 'grossiste', segment: 'A', delaiPaiement: 30, plafondCredit: 45000000, modePaiement: 'virement', totalCA: 72000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Groupe CCBM', ninea: '00198734 2G1', rccm: 'SN-DKR-2008-A-12345', email: 'commercial@ccbm.sn', phone: '+221 33 839 99 99', address: { street: 'VDN Mermoz', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', segment: 'A', delaiPaiement: 60, plafondCredit: 100000000, modePaiement: 'virement', totalCA: 150000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Sonatel Business', ninea: '00123456 3A2', rccm: 'SN-DKR-2005-A-11111', email: 'corporate@sonatel.sn', phone: '+221 33 839 12 00', address: { street: '46 Boulevard de la Republique', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'A', delaiPaiement: 30, plafondCredit: 30000000, modePaiement: 'virement', totalCA: 65000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Hotel Teranga', ninea: '00456123 1B4', rccm: 'SN-DKR-2012-B-33456', email: 'achats@teranga-hotel.sn', phone: '+221 33 889 20 00', address: { street: 'Place de l\'Independance', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'A', delaiPaiement: 30, plafondCredit: 25000000, modePaiement: 'virement', totalCA: 55000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Grands Moulins de Dakar', ninea: '00178945 0K9', rccm: 'SN-DKR-2006-A-67890', email: 'commandes@gmd.sn', phone: '+221 33 849 10 10', address: { street: 'Zone Portuaire', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'grossiste', segment: 'A', delaiPaiement: 30, plafondCredit: 40000000, modePaiement: 'virement', totalCA: 48000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'SOCOCIM Industries', ninea: '00234567 2H3', rccm: 'SN-DKR-2007-A-89012', email: 'achat@sococim.sn', phone: '+221 33 879 00 00', address: { street: 'Route de Rufisque Km 28', city: 'Rufisque', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'A', delaiPaiement: 45, plafondCredit: 35000000, modePaiement: 'virement', totalCA: 42000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Patisen SA', ninea: '00345678 1G6', rccm: 'SN-DKR-2011-A-34567', email: 'supply@patisen.sn', phone: '+221 33 859 30 00', address: { street: 'Zone Franche', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'grossiste', segment: 'A', delaiPaiement: 30, plafondCredit: 30000000, modePaiement: 'virement', totalCA: 38000000, createdBy: adminId },

    // === SEGMENT B — Next 30% (15 clients) ===
    { type: 'professionnel', raisonSociale: 'Quincaillerie Touba', ninea: '00567890 1K2', email: 'contact@quinc-touba.sn', phone: '+221 33 867 45 00', address: { street: 'Marche Sandaga', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'B', delaiPaiement: 15, plafondCredit: 5000000, modePaiement: 'cheque', totalCA: 18000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Etablissements Mbaye & Fils', ninea: '00678901 2G4', email: 'mbaye.fils@orange.sn', phone: '+221 77 456 78 90', address: { street: '12 Rue Moussé Diop', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'grossiste', segment: 'B', delaiPaiement: 30, plafondCredit: 10000000, modePaiement: 'cheque', totalCA: 22000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Super Marche Exclusive', ninea: '00712345 0H8', email: 'exclusivemarket@gmail.com', phone: '+221 33 824 56 78', address: { street: 'Almadies', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'B', delaiPaiement: 15, plafondCredit: 8000000, modePaiement: 'virement', totalCA: 15000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Restaurant Le Lagon', email: 'lelagon@orange.sn', phone: '+221 33 860 89 89', address: { street: 'Route de la Corniche', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'B', delaiPaiement: 15, plafondCredit: 3000000, modePaiement: 'cheque', totalCA: 12000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Pharmacie Guigon', ninea: '00834567 1A3', email: 'pharma.guigon@orange.sn', phone: '+221 33 821 24 76', address: { street: 'Place de l\'Independance', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'B', delaiPaiement: 30, plafondCredit: 5000000, modePaiement: 'virement', totalCA: 14000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Menuiserie Generale du Senegal', email: 'mgs@orange.sn', phone: '+221 33 834 56 00', address: { street: 'Zone Industrielle Hann', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'B', delaiPaiement: 30, plafondCredit: 7000000, modePaiement: 'cheque', totalCA: 16000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Ecole Internationale de Dakar', email: 'admin@eid.sn', phone: '+221 33 860 22 33', address: { street: 'Fann Residence', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'B', delaiPaiement: 30, plafondCredit: 10000000, modePaiement: 'virement', totalCA: 20000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Societe Generale de Banque au Senegal', ninea: '00156789 3B1', email: 'achats@sgbs.sn', phone: '+221 33 839 55 00', address: { street: '19 Avenue Leopold Sedar Senghor', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'B', delaiPaiement: 30, plafondCredit: 15000000, modePaiement: 'virement', totalCA: 25000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Transport Saloum Express', email: 'saloum.express@orange.sn', phone: '+221 77 234 56 78', address: { street: 'Gare Routiere', city: 'Kaolack', region: 'Kaolack', country: 'Senegal' }, category: 'autre', segment: 'B', delaiPaiement: 15, plafondCredit: 3000000, modePaiement: 'especes', totalCA: 8000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Clinique de la Madeleine', email: 'clinique.madeleine@orange.sn', phone: '+221 33 822 65 80', address: { street: 'Rue de la Madeleine', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'B', delaiPaiement: 30, plafondCredit: 8000000, modePaiement: 'virement', totalCA: 11000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Boulangerie Jaune', email: 'boulangerie.jaune@gmail.com', phone: '+221 77 345 67 89', address: { street: 'Parcelles Assainies U26', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'B', delaiPaiement: 7, plafondCredit: 2000000, modePaiement: 'especes', totalCA: 9000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Hotel Djoloff', email: 'hotel.djoloff@gmail.com', phone: '+221 33 889 30 30', address: { street: 'Rue Carnot', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'B', delaiPaiement: 30, plafondCredit: 5000000, modePaiement: 'virement', totalCA: 10000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Librairie Clairafrique', email: 'clairafrique@orange.sn', phone: '+221 33 822 21 69', address: { street: '2 Place de l\'Independance', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'B', delaiPaiement: 30, plafondCredit: 3000000, modePaiement: 'cheque', totalCA: 7500000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Imprimerie Nationale du Senegal', ninea: '00901234 0K5', email: 'ins@orange.sn', phone: '+221 33 823 00 00', address: { street: 'Boulevard du President L. S. Senghor', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'institutionnel', segment: 'B', delaiPaiement: 60, plafondCredit: 12000000, modePaiement: 'virement', totalCA: 19000000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Diallo Trading', email: 'diallo.trading@gmail.com', phone: '+221 77 567 89 01', address: { street: 'Marche HLM', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'grossiste', segment: 'B', delaiPaiement: 15, plafondCredit: 8000000, modePaiement: 'orange_money', totalCA: 13000000, createdBy: adminId },

    // === SEGMENT C — Bottom 50% (25 clients) ===
    { type: 'particulier', firstName: 'Moussa', lastName: 'Diop', phone: '+221 77 123 45 67', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 350000, createdBy: adminId },
    { type: 'particulier', firstName: 'Aminata', lastName: 'Sow', phone: '+221 78 234 56 78', address: { city: 'Thies', region: 'Thies', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'wave', totalCA: 280000, createdBy: adminId },
    { type: 'particulier', firstName: 'Ibrahima', lastName: 'Ndiaye', email: 'ibrahima.ndiaye@gmail.com', phone: '+221 77 345 67 89', address: { city: 'Saint-Louis', region: 'Saint-Louis', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'orange_money', totalCA: 520000, createdBy: adminId },
    { type: 'particulier', firstName: 'Fatou', lastName: 'Ba', phone: '+221 76 456 78 90', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 150000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Boutique Ndoye', phone: '+221 77 567 89 01', address: { street: 'Marche Tilene', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 1200000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Atelier Couture Elegance', phone: '+221 78 678 90 12', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 0, modePaiement: 'orange_money', totalCA: 800000, createdBy: adminId },
    { type: 'particulier', firstName: 'Ousmane', lastName: 'Gueye', phone: '+221 77 789 01 23', address: { city: 'Ziguinchor', region: 'Ziguinchor', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'wave', totalCA: 420000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Garage Auto Mecanique Plus', phone: '+221 33 855 12 34', address: { street: 'Route de l\'Aeroport', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 15, plafondCredit: 1000000, modePaiement: 'cheque', totalCA: 3500000, createdBy: adminId },
    { type: 'particulier', firstName: 'Mame', lastName: 'Thiam', phone: '+221 76 890 12 34', address: { city: 'Mbour', region: 'Thies', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 190000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Cyber Cafe Digital', phone: '+221 77 901 23 45', address: { street: 'Medina', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 0, modePaiement: 'orange_money', totalCA: 650000, createdBy: adminId },
    { type: 'particulier', firstName: 'Abdoulaye', lastName: 'Sarr', phone: '+221 78 012 34 56', address: { city: 'Kaolack', region: 'Kaolack', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 270000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Pressing Nettoyage Express', phone: '+221 77 123 78 90', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 7, modePaiement: 'especes', totalCA: 1800000, createdBy: adminId },
    { type: 'particulier', firstName: 'Aissatou', lastName: 'Diallo', email: 'aissatou.diallo@yahoo.fr', phone: '+221 76 234 56 78', address: { city: 'Tambacounda', region: 'Tambacounda', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'wave', totalCA: 380000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Poissonnerie du Port', phone: '+221 77 345 89 01', address: { street: 'Port de Peche', city: 'Mbour', region: 'Thies', country: 'Senegal' }, category: 'detaillant', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 2500000, createdBy: adminId },
    { type: 'particulier', firstName: 'Cheikh', lastName: 'Fall', phone: '+221 78 456 90 12', address: { city: 'Louga', region: 'Louga', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'orange_money', totalCA: 310000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Salon de Coiffure Prestige', phone: '+221 77 567 01 23', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 450000, createdBy: adminId },
    { type: 'particulier', firstName: 'Ndeye', lastName: 'Kane', phone: '+221 76 678 12 34', address: { city: 'Pikine', region: 'Dakar', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'wave', totalCA: 220000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Mini Market Touba', phone: '+221 77 789 23 45', address: { city: 'Touba', region: 'Diourbel', country: 'Senegal' }, category: 'detaillant', segment: 'C', delaiPaiement: 7, plafondCredit: 500000, modePaiement: 'orange_money', totalCA: 4200000, createdBy: adminId },
    { type: 'particulier', firstName: 'Modou', lastName: 'Mbaye', phone: '+221 78 890 34 56', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 180000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Ferme Avicole de Sangalkam', phone: '+221 33 836 45 67', address: { city: 'Sangalkam', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 15, plafondCredit: 2000000, modePaiement: 'cheque', totalCA: 5800000, createdBy: adminId },
    { type: 'particulier', firstName: 'Mariama', lastName: 'Sy', phone: '+221 76 901 45 67', address: { city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'wave', totalCA: 290000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Alimentation Generale Keur Serigne', phone: '+221 77 012 56 78', address: { street: 'Guediawaye', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'detaillant', segment: 'C', delaiPaiement: 7, plafondCredit: 300000, modePaiement: 'especes', totalCA: 3100000, createdBy: adminId },
    { type: 'particulier', firstName: 'Boubacar', lastName: 'Diouf', phone: '+221 78 123 67 89', address: { city: 'Fatick', region: 'Fatick', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'orange_money', totalCA: 160000, createdBy: adminId },
    { type: 'particulier', firstName: 'Khady', lastName: 'Toure', phone: '+221 76 234 78 90', address: { city: 'Kolda', region: 'Kolda', country: 'Senegal' }, category: 'particulier', segment: 'C', delaiPaiement: 0, modePaiement: 'especes', totalCA: 95000, createdBy: adminId },
    { type: 'professionnel', raisonSociale: 'Menuiserie Metallique Ndiaye', phone: '+221 77 345 89 01', address: { street: 'Zone Artisanale Colobane', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'autre', segment: 'C', delaiPaiement: 15, plafondCredit: 1500000, modePaiement: 'especes', totalCA: 4500000, createdBy: adminId },
  ];
};

module.exports = getClientsData;
