/**
 * Generate 20 realistic Senegalese suppliers
 * @param {string} adminId - Admin user ObjectId for createdBy
 */
const getFournisseursData = (adminId) => {
  return [
    { raisonSociale: 'SONACOS - Societe Nationale de Commercialisation', ninea: '00112233 2K1', rccm: 'SN-DKR-2005-A-11234', email: 'ventes@sonacos.sn', phone: '+221 33 849 21 00', address: { street: 'Route de Rufisque', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'fabricant', delaiPaiement: 30, delaiLivraison: 3, rating: { qualite: 4, delai: 4, prix: 3, service: 4 }, bankInfo: { bankName: 'CBAO', accountNumber: '0123456789', iban: 'SN08SN0001012345678901', swift: 'CBAOSNDA' }, createdBy: adminId },
    { raisonSociale: 'Patisen SA', ninea: '00223344 1G5', rccm: 'SN-DKR-2008-A-22345', email: 'grossiste@patisen.sn', phone: '+221 33 859 31 00', address: { street: 'Zone Franche Industrielle', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'fabricant', delaiPaiement: 45, delaiLivraison: 2, rating: { qualite: 5, delai: 4, prix: 3, service: 5 }, createdBy: adminId },
    { raisonSociale: 'Nestle Senegal', ninea: '00334455 0H7', rccm: 'SN-DKR-2003-A-33456', email: 'orders@nestle.sn', phone: '+221 33 869 40 00', address: { street: 'Zone Industrielle', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'international', delaiPaiement: 60, delaiLivraison: 5, rating: { qualite: 5, delai: 3, prix: 2, service: 4 }, createdBy: adminId },
    { raisonSociale: 'SIMPA - Societe Industrielle Moderne', ninea: '00445566 2G3', email: 'commandes@simpa.sn', phone: '+221 33 839 50 00', address: { street: 'VDN', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', delaiPaiement: 30, delaiLivraison: 2, rating: { qualite: 4, delai: 5, prix: 4, service: 4 }, createdBy: adminId },
    { raisonSociale: 'Buhan & Teisseire Senegal', ninea: '00556677 1K9', email: 'supply@buhan-teisseire.sn', phone: '+221 33 823 10 00', address: { street: 'Rue Parchappe', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', delaiPaiement: 30, delaiLivraison: 3, rating: { qualite: 4, delai: 4, prix: 3, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Import-Export El Hadj Diouf', email: 'import.diouf@orange.sn', phone: '+221 77 456 12 34', address: { street: 'Marche Sandaga', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'local', delaiPaiement: 15, delaiLivraison: 1, rating: { qualite: 3, delai: 5, prix: 5, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Guangzhou Trading Co.', email: 'senegal@guangzhou-trading.cn', phone: '+86 20 8888 7777', address: { street: '888 Baiyun Road', city: 'Guangzhou', region: 'Guangdong', country: 'Chine' }, category: 'international', delaiPaiement: 90, delaiLivraison: 45, devises: 'USD', rating: { qualite: 3, delai: 2, prix: 5, service: 2 }, createdBy: adminId },
    { raisonSociale: 'Comptoir Commercial du Senegal', ninea: '00667788 0A2', email: 'ventes@ccs.sn', phone: '+221 33 823 45 00', address: { street: '8 Rue de Thann', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', delaiPaiement: 30, delaiLivraison: 2, rating: { qualite: 4, delai: 4, prix: 4, service: 4 }, createdBy: adminId },
    { raisonSociale: 'Dubai Wholesale FZE', email: 'africa@dubai-wholesale.ae', phone: '+971 4 234 5678', address: { street: 'Jebel Ali Free Zone', city: 'Dubai', country: 'Emirats Arabes Unis' }, category: 'international', delaiPaiement: 60, delaiLivraison: 21, devises: 'USD', rating: { qualite: 4, delai: 3, prix: 4, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Societe des Brasseries de l\'Ouest Africain', ninea: '00778899 1B4', email: 'distribution@soboa.sn', phone: '+221 33 839 60 00', address: { street: 'Route des Brasseries', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'fabricant', delaiPaiement: 15, delaiLivraison: 1, rating: { qualite: 5, delai: 5, prix: 3, service: 5 }, createdBy: adminId },
    { raisonSociale: 'CFAO Technologies Senegal', ninea: '00889900 2G6', email: 'commandes@cfao-tech.sn', phone: '+221 33 849 70 00', address: { street: 'VDN Ngor', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'distributeur', delaiPaiement: 45, delaiLivraison: 7, rating: { qualite: 5, delai: 3, prix: 2, service: 4 }, createdBy: adminId },
    { raisonSociale: 'Papeterie Moderne du Senegal', email: 'commande@papeterie-moderne.sn', phone: '+221 33 822 30 00', address: { street: 'Rue Abdou Karim Bourgi', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'local', delaiPaiement: 30, delaiLivraison: 2, rating: { qualite: 4, delai: 4, prix: 4, service: 4 }, createdBy: adminId },
    { raisonSociale: 'Materiel BTP Afrique', email: 'contact@materiel-btp.sn', phone: '+221 33 834 80 00', address: { street: 'Zone Industrielle Hann', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'local', delaiPaiement: 30, delaiLivraison: 5, rating: { qualite: 3, delai: 3, prix: 4, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Senegalaise des Eaux Minerales', ninea: '00990011 1K8', email: 'commercial@sem.sn', phone: '+221 33 859 90 00', address: { city: 'Thies', region: 'Thies', country: 'Senegal' }, category: 'fabricant', delaiPaiement: 15, delaiLivraison: 1, rating: { qualite: 4, delai: 5, prix: 4, service: 4 }, createdBy: adminId },
    { raisonSociale: 'Istanbul Commerce SARL', email: 'senegal@istanbul-commerce.com', phone: '+90 212 555 6677', address: { city: 'Istanbul', country: 'Turquie' }, category: 'international', delaiPaiement: 60, delaiLivraison: 30, devises: 'EUR', rating: { qualite: 4, delai: 3, prix: 5, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Societe de Distribution de Materiel Agricole', email: 'ventes@sdma.sn', phone: '+221 33 951 20 00', address: { city: 'Thies', region: 'Thies', country: 'Senegal' }, category: 'distributeur', delaiPaiement: 30, delaiLivraison: 5, rating: { qualite: 4, delai: 3, prix: 3, service: 4 }, createdBy: adminId },
    { raisonSociale: 'Quincaillerie Khadim', email: 'khadim.quinc@orange.sn', phone: '+221 77 678 90 12', address: { street: 'Avenue Blaise Diagne', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'local', delaiPaiement: 15, delaiLivraison: 1, rating: { qualite: 3, delai: 5, prix: 5, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Cosmivoire CI', email: 'export@cosmivoire.ci', phone: '+225 27 21 35 00 00', address: { city: 'Abidjan', country: 'Cote d\'Ivoire' }, category: 'international', delaiPaiement: 30, delaiLivraison: 10, devises: 'XOF', rating: { qualite: 4, delai: 3, prix: 4, service: 3 }, createdBy: adminId },
    { raisonSociale: 'Imprimerie Tunde', email: 'contact@tunde-print.sn', phone: '+221 33 832 45 00', address: { street: 'Zone Industrielle', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'prestataire', delaiPaiement: 15, delaiLivraison: 3, rating: { qualite: 4, delai: 4, prix: 4, service: 5 }, createdBy: adminId },
    { raisonSociale: 'Senegal Pieces Auto', email: 'pieces@spa.sn', phone: '+221 33 824 56 00', address: { street: 'Colobane', city: 'Dakar', region: 'Dakar', country: 'Senegal' }, category: 'local', delaiPaiement: 15, delaiLivraison: 1, rating: { qualite: 3, delai: 5, prix: 4, service: 3 }, createdBy: adminId },
  ];
};

module.exports = getFournisseursData;
